### ISSUE TITLE
Increase websocket timeout

### ISSUE THREAD

**Issue by andrewosh** [oasislabs/devnet-issues#3]
## Feature request

**What is the desired feature?**
The websocket timeout was recently decreased from 60 min to 1 min. While a lower timeout makes sense, 1 minute is low enough that it'll affect usage in my application. I can reasonably expect users to sit idly on the page for up to 5 or 10 minutes -- after that, a page refresh is reasonable.

**What is motivation or use-case for this feature?**
With a 60s timeout, we'll either have to a) have a regular heartbeat or b) replace the `WebsocketProvider` after an `end` event. The former will still hog resources on your end if there are many inactive tabs. The latter might introduce unforeseen issues (I'm seeing that when the provider is replaced with `setProvider`, the new provider doesn't have the same set of `responseCallbacks`. I'm not sure what those callbacks are, but if they're necessary for internal bookkeeping, then something's off).

**How should this be implemented/designed in your opinion? (optional)**
Bump that timeout to 10 min!

**Are you willing to help us test this feature? (optional)**
Willing and able :)

**Comment by peterjgilbert** [comment]
The effective idle timeout value is now 100 seconds.
